services:
  - type: web
    name: data-analytics-dashboard
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: GROQ_API_KEY
        sync: false
    autoDeploy: true 